"""收回 Data API 权限迁移（20261001150000）的数据库级测试 —— 在嵌入式 Postgres 上模拟 Supabase 生产状态。

模拟的生产事实（来自 docs/reviews/2026-10-01-revoke-public-api-grants-review.md 的只读核查）：
- postgres 与 supabase_admin 都配置了 public 默认 ACL，向 anon/authenticated 授予表与序列权限
- 仓库迁移建出 69 张 funeng 表，其中 40 张对 anon/authenticated 有授权，29 张为后端专用（无授权）
- 另有非 funeng 的 todos 表（authenticated 按 auth.uid 访问的 4 条策略）
- products/categories/lands/crops/farm_info 有 USING(true) 的公开读取策略

运行（需 Python 3.12，pgserver 自带 Postgres，无需本机安装）：
    uv run --python 3.12 --with pgserver --with "psycopg[binary]" --with pytest pytest -q supabase/tests
"""
import itertools
import tempfile
from pathlib import Path

import pgserver
import psycopg
import pytest

ROOT = Path(__file__).resolve().parents[2]
MIGRATIONS = ROOT / "supabase" / "migrations"
REVOKE = (MIGRATIONS / "20261001150000_revoke_public_api_grants.sql").read_text(encoding="utf-8")
ROLLBACK = (ROOT / "supabase" / "rollback" / "20261001150000_revoke_public_api_grants.rollback.sql").read_text(encoding="utf-8")
PRIOR_MIGRATIONS = [
    "20260929_funeng_baseline.sql",
    "20260929_funeng_merge_conflict_audit.sql",
    "20260930232846_agri_industry_snapshot_storage.sql",
    "20261001120000_funeng_business_module_tables.sql",
]
PUBLIC_READ_TABLES = ["products", "categories", "lands", "crops", "farm_info"]
TEMPLATE = "funeng_supabase_tpl"
_counter = itertools.count()


@pytest.fixture(scope="session")
def server():
    srv = pgserver.get_server(tempfile.mkdtemp(prefix="revoke-test-"), cleanup_mode="stop")
    admin = psycopg.connect(srv.get_uri(), autocommit=True)
    for role in ("anon", "authenticated", "service_role", "supabase_admin"):
        admin.execute(f"DO $$BEGIN CREATE ROLE {role}; EXCEPTION WHEN duplicate_object THEN NULL; END$$;")
    admin.execute(f"DROP DATABASE IF EXISTS {TEMPLATE}")
    admin.execute(f"CREATE DATABASE {TEMPLATE}")
    uri = srv.get_uri(TEMPLATE)
    with psycopg.connect(uri, autocommit=True) as c:
        c.execute("CREATE SCHEMA storage; CREATE TABLE storage.buckets (id text primary key, name text, public bool)")
        c.execute("CREATE SCHEMA auth; CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS 'SELECT NULL::uuid'")
        c.execute("GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role, supabase_admin")
        c.execute("GRANT CREATE ON SCHEMA public TO supabase_admin")
        for creator in ("postgres", "supabase_admin"):
            c.execute(f"ALTER DEFAULT PRIVILEGES FOR ROLE {creator} IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role")
            c.execute(f"ALTER DEFAULT PRIVILEGES FOR ROLE {creator} IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role")
        for name in PRIOR_MIGRATIONS:
            c.execute((MIGRATIONS / name).read_text(encoding="utf-8"))
        # 非 funeng 应用的表与策略
        c.execute("""
            CREATE TABLE public.todos (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid, task text);
            ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;
            CREATE POLICY todos_select ON public.todos FOR SELECT TO authenticated USING (auth.uid() = user_id);
            CREATE POLICY todos_insert ON public.todos FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
            CREATE POLICY todos_update ON public.todos FOR UPDATE TO authenticated USING (auth.uid() = user_id);
            CREATE POLICY todos_delete ON public.todos FOR DELETE TO authenticated USING (auth.uid() = user_id);
        """)
        for t in PUBLIC_READ_TABLES:
            c.execute(f"CREATE POLICY public_read ON public.{t} FOR SELECT USING (true)")
    yield srv
    admin.execute(f"DROP DATABASE IF EXISTS {TEMPLATE}")


@pytest.fixture
def db(server):
    name = f"t{next(_counter)}"
    admin = psycopg.connect(server.get_uri(), autocommit=True)
    admin.execute(f"CREATE DATABASE {name} TEMPLATE {TEMPLATE}")
    conn = psycopg.connect(server.get_uri(name), autocommit=True)
    yield conn
    conn.close()
    admin.execute(f"DROP DATABASE {name}")


# ---------- helpers ----------

# ACL 是授权项的集合，项的先后顺序不影响权限；比较时按项排序（保留 grantee、权限、授权选项与 grantor）
_SORTED_ACL = "(SELECT string_agg(x::text, ',' ORDER BY x::text) FROM unnest({col}) x)"


def acl_state(conn):
    """public 下全部关系的表级/列级 ACL，以及 public 默认 ACL —— 用于「前后完全一致」比较。"""
    rels = dict(conn.execute(f"""
        SELECT c.relname, coalesce({_SORTED_ACL.format(col='c.relacl')}, '') || '|' || coalesce(
          (SELECT string_agg(a.attname || '=' || {_SORTED_ACL.format(col='a.attacl')}, ';' ORDER BY a.attnum)
             FROM pg_attribute a WHERE a.attrelid = c.oid AND a.attacl IS NOT NULL), '')
        FROM pg_class c WHERE c.relnamespace = 'public'::regnamespace AND c.relkind IN ('r','p','v','m','f','S')
    """).fetchall())
    defaults = conn.execute(f"""
        SELECT pg_get_userbyid(defaclrole), defaclobjtype::text, {_SORTED_ACL.format(col='defaclacl')} FROM pg_default_acl
        WHERE defaclnamespace = 'public'::regnamespace ORDER BY 1, 2
    """).fetchall()
    return rels, defaults


def anon_effective_tables(conn, role="anon"):
    return {r[0] for r in conn.execute("""
        SELECT c.relname FROM pg_class c
        WHERE c.relnamespace = 'public'::regnamespace AND c.relkind IN ('r','p','v','m','f')
          AND (has_table_privilege(%s, c.oid, 'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')
               OR has_any_column_privilege(%s, c.oid, 'SELECT,INSERT,UPDATE,REFERENCES'))
    """, (role, role)).fetchall()}


def funeng_tables(conn):
    return {r[0] for r in conn.execute("""
        SELECT relname FROM pg_class WHERE relnamespace = 'public'::regnamespace AND relkind = 'r' AND relname <> 'todos'
    """).fetchall()}


def apply_revoke_expect_failure(conn, fragment):
    before = acl_state(conn)
    with pytest.raises(psycopg.errors.RaiseException) as err:
        conn.execute(REVOKE)
    conn.execute("ROLLBACK")
    assert fragment in str(err.value)
    assert acl_state(conn) == before, "failed run must leave no partial changes"
    assert conn.execute("SELECT to_regclass('funeng_ops.acl_snapshot')").fetchone()[0] is None


# ---------- 基线与范围 ----------

def test_template_reflects_production_facts(db):
    assert len(funeng_tables(db)) == 69
    granted = anon_effective_tables(db)
    assert len(granted) == 41 and "todos" in granted          # 40 funeng + todos
    assert len(funeng_tables(db) - granted) == 29              # 后端专用表


def test_revokes_effective_access_on_all_funeng_objects(db):
    db.execute(REVOKE)
    for role in ("anon", "authenticated"):
        assert anon_effective_tables(db, role) == {"todos"}
    leftover_seq = db.execute("""
        SELECT count(*) FROM pg_class s
        WHERE s.relnamespace = 'public'::regnamespace AND s.relkind = 'S' AND s.relname NOT LIKE 'todos%%'
          AND (has_sequence_privilege('anon', s.oid, 'USAGE,SELECT,UPDATE') OR has_sequence_privilege('authenticated', s.oid, 'USAGE,SELECT,UPDATE'))
    """).fetchone()[0]
    assert leftover_seq == 0
    # service_role 与属主不受影响
    assert db.execute("SELECT has_table_privilege('service_role', 'public.products', 'SELECT')").fetchone()[0]
    db.execute("INSERT INTO public.categories (name) VALUES ('owner-still-writes')")


def test_public_read_policies_no_longer_reachable_but_kept(db):
    db.execute(REVOKE)
    for t in PUBLIC_READ_TABLES:
        assert not db.execute(f"SELECT has_table_privilege('anon', 'public.{t}', 'SELECT')").fetchone()[0]
    assert db.execute("SELECT count(*) FROM pg_policies WHERE policyname = 'public_read'").fetchone()[0] == 5


def test_non_funeng_objects_untouched(db):
    before_rels, _ = acl_state(db)
    policies_before = db.execute("SELECT policyname, cmd, roles::text, qual FROM pg_policies WHERE tablename = 'todos' ORDER BY 1").fetchall()
    db.execute(REVOKE)
    after_rels, _ = acl_state(db)
    for name in ("todos", "todos_id_seq"):
        assert after_rels[name] == before_rels[name]
    assert db.execute("SELECT policyname, cmd, roles::text, qual FROM pg_policies WHERE tablename = 'todos' ORDER BY 1").fetchall() == policies_before


# ---------- 回滚精确恢复（review R1） ----------

def test_rollback_restores_exact_original_acl(db):
    before = acl_state(db)
    db.execute(REVOKE)
    db.execute(ROLLBACK)
    assert acl_state(db) == before


def test_rollback_does_not_open_private_tables(db):
    private = funeng_tables(db) - anon_effective_tables(db)
    db.execute(REVOKE)
    db.execute(ROLLBACK)
    assert private.isdisjoint(anon_effective_tables(db))
    assert private.isdisjoint(anon_effective_tables(db, "authenticated"))


def test_idempotent_and_snapshot_kept_from_first_run(db):
    db.execute(REVOKE)
    snap = db.execute("SELECT count(*) FROM funeng_ops.acl_snapshot").fetchone()[0]
    db.execute(REVOKE)
    assert db.execute("SELECT count(*) FROM funeng_ops.acl_snapshot").fetchone()[0] == snap > 0
    before_rollback_target = acl_state(db)
    db.execute(ROLLBACK)
    db.execute(REVOKE)
    assert acl_state(db) == before_rollback_target


def test_snapshot_not_exposed_to_api_roles(db):
    db.execute(REVOKE)
    for role in ("anon", "authenticated"):
        assert not db.execute(f"SELECT has_schema_privilege('{role}', 'funeng_ops', 'USAGE')").fetchone()[0]
        assert not db.execute(f"SELECT has_table_privilege('{role}', 'funeng_ops.acl_snapshot', 'SELECT')").fetchone()[0]


# ---------- 残留有效权限检测（review R3） ----------

def test_detects_grant_via_public(db):
    db.execute("GRANT SELECT ON public.products TO PUBLIC")
    apply_revoke_expect_failure(db, "effective table/column privileges remain")


def test_detects_grant_via_inherited_role(db):
    db.execute("CREATE ROLE api_reader NOLOGIN; GRANT SELECT ON public.farm_info TO api_reader; GRANT api_reader TO anon")
    apply_revoke_expect_failure(db, "farm_info(anon)")


def test_sequence_select_only_is_revoked_and_restored(db):
    seq = "products_id_seq"
    db.execute(f"REVOKE ALL ON SEQUENCE public.{seq} FROM anon; GRANT SELECT ON SEQUENCE public.{seq} TO anon")
    before = acl_state(db)
    db.execute(REVOKE)
    assert not db.execute(f"SELECT has_sequence_privilege('anon', 'public.{seq}', 'USAGE,SELECT,UPDATE')").fetchone()[0]
    db.execute(ROLLBACK)
    assert acl_state(db) == before


def test_column_level_grant_is_revoked_and_restored(db):
    # 先去掉表级授权，只留列级 SELECT(name)
    db.execute("REVOKE ALL ON public.farm_info FROM anon; GRANT SELECT (name) ON public.farm_info TO anon")
    before = acl_state(db)
    db.execute(REVOKE)
    assert not db.execute("SELECT has_any_column_privilege('anon', 'public.farm_info', 'SELECT')").fetchone()[0]
    db.execute(ROLLBACK)
    assert acl_state(db) == before


def test_target_not_owned_by_postgres_aborts(db):
    db.execute("ALTER TABLE public.crops OWNER TO supabase_admin")
    apply_revoke_expect_failure(db, "not owned by postgres")


# ---------- 默认权限范围（review 补充：只覆盖 postgres） ----------

def test_default_privileges_scope_is_postgres_only(db):
    db.execute(REVOKE)
    db.execute("CREATE TABLE public.zz_by_postgres (id int)")
    db.execute("SET ROLE supabase_admin; CREATE TABLE public.zz_by_supabase_admin (id int); RESET ROLE")
    assert not db.execute("SELECT has_table_privilege('anon', 'public.zz_by_postgres', 'SELECT')").fetchone()[0]
    # 本迁移不修改 supabase_admin 的默认 ACL：其新建对象仍会开放，需另行处理（文档已注明）
    assert db.execute("SELECT has_table_privilege('anon', 'public.zz_by_supabase_admin', 'SELECT')").fetchone()[0]
