-- Apply once through a privileged migration connection before --write-db.
-- Market quotes are intentionally separate from product inventory.
CREATE TABLE IF NOT EXISTS public.market_price_observations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_key varchar(64) NOT NULL UNIQUE,
    source_id varchar(40) NOT NULL,
    source_url text NOT NULL,
    market_name varchar(180) NOT NULL,
    province varchar(80) NOT NULL DEFAULT '',
    category varchar(40) NOT NULL,
    commodity varchar(180) NOT NULL,
    specification varchar(180) NOT NULL DEFAULT '',
    origin varchar(180) NOT NULL DEFAULT '',
    observed_date date NOT NULL,
    period_start date,
    period_end date,
    quote_type varchar(60) NOT NULL,
    source_unit varchar(40) NOT NULL,
    price_min numeric(12,4),
    price_avg numeric(12,4),
    price_max numeric(12,4),
    price_min_yuan_per_kg numeric(12,4),
    price_avg_yuan_per_kg numeric(12,4),
    price_max_yuan_per_kg numeric(12,4),
    quality_flag varchar(40) NOT NULL,
    source_row_key varchar(100) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS market_price_observations_date_idx
    ON public.market_price_observations (observed_date DESC, category);
ALTER TABLE public.market_price_observations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.market_price_observations FROM anon, authenticated;
