-- Source-attributed datasets. Existing products, orders and users are untouched.
CREATE TABLE IF NOT EXISTS public.market_price_observations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_key varchar(64) NOT NULL UNIQUE,
    source_id varchar(40) NOT NULL,
    source_url text NOT NULL,
    market_name varchar(180) NOT NULL,
    province varchar(80) NOT NULL DEFAULT '',
    category varchar(40) NOT NULL,
    commodity varchar(180) NOT NULL,
    specification varchar(180) NOT NULL DEFAULT '',
    origin varchar(180) NOT NULL DEFAULT '',
    observed_date date NOT NULL,
    period_start date,
    period_end date,
    quote_type varchar(60) NOT NULL,
    source_unit varchar(40) NOT NULL,
    price_min numeric(12,4), price_avg numeric(12,4), price_max numeric(12,4),
    price_min_yuan_per_kg numeric(12,4), price_avg_yuan_per_kg numeric(12,4),
    price_max_yuan_per_kg numeric(12,4),
    quality_flag varchar(40) NOT NULL,
    source_row_key varchar(100) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS market_price_observations_date_idx
    ON public.market_price_observations(observed_date DESC, category);
CREATE TABLE public.agri_data_sources (
    source_id text PRIMARY KEY,
    name text NOT NULL,
    domain text NOT NULL CHECK (domain IN ('market', 'industry')),
    source_url text,
    status text NOT NULL CHECK (status IN ('collected', 'manual_reviewed', 'reference_only', 'pending')),
    coverage text NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (status = 'pending' OR source_url IS NOT NULL)
);
CREATE TABLE public.industry_observations (
    external_key text PRIMARY KEY CHECK (external_key ~ '^[a-f0-9]{64}$'),
    source_id text NOT NULL REFERENCES public.agri_data_sources(source_id),
    source_url text NOT NULL,
    metric text NOT NULL,
    metric_name text NOT NULL,
    region text NOT NULL,
    category text NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL CHECK (period_end >= period_start),
    frequency text NOT NULL CHECK (frequency IN ('annual', 'quarterly', 'monthly', 'daily', 'weekly')),
    value numeric NOT NULL CHECK (value >= 0 AND value NOT IN ('NaN'::numeric, 'Infinity'::numeric)),
    unit text NOT NULL,
    measure_type text NOT NULL,
    qualifier text NOT NULL CHECK (qualifier IN ('exact', 'gt', 'ge', 'approx')),
    yoy_percent numeric CHECK (yoy_percent NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)),
    evidence text NOT NULL,
    review_status text NOT NULL CHECK (review_status IN ('collected', 'manual_reviewed')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX industry_observations_lookup_idx ON public.industry_observations(metric, region, period_end DESC);
CREATE INDEX industry_observations_source_idx ON public.industry_observations(source_id);
CREATE TABLE public.cold_chain_reference_nodes (
    external_key text PRIMARY KEY CHECK (external_key ~ '^[a-f0-9]{64}$'),
    source_id text NOT NULL REFERENCES public.agri_data_sources(source_id),
    source_url text NOT NULL,
    name text NOT NULL,
    province text NOT NULL,
    city text NOT NULL,
    reported text NOT NULL,
    scope text NOT NULL,
    snapshot_date date NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX cold_chain_reference_nodes_province_idx ON public.cold_chain_reference_nodes(province);
CREATE INDEX cold_chain_reference_nodes_source_idx ON public.cold_chain_reference_nodes(source_id);
CREATE TABLE public.agri_data_import_runs (
    snapshot_sha256 text PRIMARY KEY CHECK (snapshot_sha256 ~ '^[a-f0-9]{64}$'),
    status text NOT NULL CHECK (status = 'completed'),
    manifest jsonb NOT NULL,
    verification jsonb,
    verified_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.market_price_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agri_data_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.industry_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cold_chain_reference_nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agri_data_import_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.agri_data_sources, public.market_price_observations,
    public.industry_observations, public.cold_chain_reference_nodes,
    public.agri_data_import_runs FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.agri_data_sources, public.market_price_observations,
    public.industry_observations, public.cold_chain_reference_nodes,
    public.agri_data_import_runs TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.market_price_observations_id_seq TO service_role;
COMMENT ON TABLE public.market_price_observations IS 'Public market quotes, national averages and milk producer prices; separate from product inventory.';
COMMENT ON TABLE public.industry_observations IS 'Source-attributed statistics; overlapping credit categories must not be summed. gt records are lower bounds.';
COMMENT ON TABLE public.cold_chain_reference_nodes IS 'Reviewed subset of public cold-chain nodes; reported capacity is not available inventory.';
COMMENT ON TABLE public.agri_data_sources IS 'Source registry including pending integrations. Pending sources have no synthetic zero observations.';
COMMENT ON TABLE public.agri_data_import_runs IS 'Idempotent reviewed snapshot imports and verification manifests; no credentials.';
