CREATE TABLE IF NOT EXISTS public.funeng_migration_conflicts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_table text NOT NULL,
    source_pk text NOT NULL,
    local_values jsonb NOT NULL,
    remote_values jsonb NOT NULL,
    recorded_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT funeng_migration_conflicts_source_unique UNIQUE (source_table, source_pk)
);
ALTER TABLE public.funeng_migration_conflicts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.funeng_migration_conflicts FROM anon, authenticated;
COMMENT ON TABLE public.funeng_migration_conflicts IS 'Audited local SQLite values that conflicted with preexisting Supabase records during 2026-09-29 merge; never stores passwords.';
